In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

from train_nn import *

Using TensorFlow backend.


In [12]:
# Load pre-trained neural network models from pickle file
model_bag_of_words = pickle.load(open( "../neural_network_bag_of_words_v2.pickle", "rb" ))
model_pos_specific = pickle.load(open( "../neural_network_pos_specific_v2.pickle", "rb" ))

# Create pd dataframe of sequence information 
degron_pred = pd.read_csv("../degron_pred.csv", index_col=0)
# Select column of input sequences
input_seq = degron_pred.iloc[:, 10]

In [13]:
# Use compute_feature_matrix function to encode sequences
features = compute_feature_matrix(input_seq, 6, True)
condensed_features = features[:, 0:20] # Remove zeros at the end for bag of words prediction

In [14]:
# Use pre-trained model to predict sequence degredataion
pred_bow = model_bag_of_words.predict_proba(condensed_features) # bag of words prediction
pred_ps = model_pos_specific.predict_proba(features) # position-specific prediction

In [15]:
drp = pred_ps-pred_bow
drp[0:10]

array([[-0.43807366],
       [-0.03768384],
       [-0.55850381],
       [ 0.05132312],
       [ 0.01944852],
       [-0.32106578],
       [-0.23207328],
       [-0.74083978],
       [-0.24626228],
       [-0.13040398]], dtype=float32)

In [25]:
len(input_seq)

16256

In [27]:
input_seq[16255]

'PPAPPPPNILPTPSLELEEAEEQ'

In [31]:
# def mutate(seq, index, newchar):
#     char_list = list(seq)
#     char_list[index] = newchar
#     return "".join(char_list)

In [33]:
input_seq[i+1][pos]

'N'

In [34]:
 mutate(input_seq[i], pos, input_seq[i+1][pos])

'NLTDYGELSDWSLPATATMSLGK'

In [48]:
# Convert string to lists

seqlist = [] # 2D list of all sequences, with each character as 1 entry 
for sequence in input_seq:
    seqlist.append(list(sequence))

In [55]:
# Mutation 1: Shift mutation
# Shifts all the characters at a certin position down by 1 sequence, with the first sequence
# filled by the last sequence

seq_length = len(seqlist[0]) # 23
num_seq = len(seqlist)       # number of total sequences
shift = 1                    # distance to shift characters by

pos = 0 # revise this later
first = seqlist[0][pos]
for i in range(num_seq-shift):
    #for j in range(seq_length) - iterate through positions
    seqlist[i][pos] = seqlist[i+shift][pos]
seqlist[num_seq-shift][pos]=first


NameError: name 'mutated_seq' is not defined

In [56]:
mutated_seq = []
for i in range(num_seq):
    mutated_seq.append("".join(seqlist[i])) 

In [71]:
# Use compute_feature_matrix function to encode sequences
features = compute_feature_matrix(pd.Series(mutated_seq), 6, True)
condensed_features = features[:, 0:20] # Remove zeros at the end for bag of words prediction

In [72]:
# Use pre-trained model to predict sequence degredataion
pred_bow = model_bag_of_words.predict_proba(condensed_features) # bag of words prediction
pred_ps = model_pos_specific.predict_proba(features) # position-specific prediction

In [73]:
drp2 = pred_ps-pred_bow

In [79]:
diff = drp-drp2

In [87]:
vect = np.asarray(diff[:, 0])

In [89]:
np.histogram(vect)

(array([  34,  108,  290,  955, 9962, 3827,  726,  255,   80,   19]),
 array([-0.78543741, -0.62324376, -0.46105011, -0.29885646, -0.13666281,
         0.02553084,  0.18772449,  0.34991814,  0.51211179,  0.67430544,
         0.83649909]))

In [90]:
import matplotlib.pyplot as plt

In [91]:
plt.hist(vect, bins='auto')

(array([  2.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   2.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   2.00000000e+00,
          2.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   2.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   0.00000000e+00,   2.00000000e+00,
          3.00000000e+00,   2.00000000e+00,   2.00000000e+00,
          2.00000000e+00,   3.00000000e+00,   2.00000000e+00,
          2.00000000e+00,   0.00000000e+00,   2.00000000e+00,
          3.00000000e+00,   3.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   3.00000000e+00,   1.00000000e+00,
          2.00000000e+00,   6.00000000e+00,   8.00000000e+00,
          1.00000000e+00,   1.00000000e+00,   4.00000000e+00,
          5.00000000e+00,   3.00000000e+00,   6.00000000e+00,
          3.00000000e+00,   3.00000000e+00,   3.00000000e+00,
        